### ISSUE TITLE
6/10 회의 - Unit Test 추가 내용

### ISSUE THREAD

**Issue by ngwoon** [sys09270883/alarm-customizing-clock-system#56]
전체적으로 --> 모드 전환 시에 모드 제대로 바뀌는지

1. Timekeeping

- 년, 월, 일, 시, 분, 초가 경계값을 넘어가는지

- 설정 중에 조작한 월에 따라서 일이 제대로 맞춰지는지

- 고의적으로 월에 맞지 않는 일로 설정한 후 저장하면 저장되지 않는지

- 알람 수, 디데이가 동기화 되는지
(alarmCnt, d_day 변수 값확인)

2. Stopwatch

- resetStopwatchTest에 pause된 상태에서도 reset 되는지 확인

- controltest에서 포인터의 경계값 확인

- 기록이 없을 때, requestRecordCheckMode()를 실행해도 모드가 바뀌지 않는지 확인

3. Timer

- 시, 분, 초 경계값 확인

- resetTimerTest에서 pause된 상태에서도 reset 되는지 확인

4. D day

- 년, 월, 일 경계값 확인

- 설정 중에 조작한 월에 따라서 일이 제대로 맞춰지는지

- 고의적으로 월에 맞지 않는 일로 설정한 후 저장하면 저장되지 않는지

5. Alarm

- 시, 분, 초 경계값 확인

- alarmControl 경계값 확인

- 알람이 없으면 알람 선택 모드로 진입하지 않는지 확인

6. AlarmCustom

- 알람이 없으면 알람 선택 모드로 진입하지 않는지 확인

* buzzer 볼륨 5단계로 수정 필요

**Comment by sys09270883** [comment]
수정완료
