### ISSUE TITLE
Timeout 기능 관련

### ISSUE THREAD

**Issue by ngwoon** [sys09270883/alarm-customizing-clock-system#8]
timeout(), cancel() 함수를 Function 클래스에서 갖고 있지 않고, System이 관리하는 식으로의 구현

(timeout() 함수명을 startCheckTimeOut()으로 표현했습니다.)

timeout 기능 구현 방법
1. selectBtnPressed 에서 모드가 0 -> 1로 바뀔 때 startCheckTimeOut() 함수를 호출한다.
    - startCheckTimeOut() 함수는 시간 체크 쓰레드를 시작. 현재 사용중인 기능의 최근 조작 시간과 
      현재 시간을 비교하여 이 차이가 10분인지를 지속적으로 확인한다.

2. startCheckTimeOut()에서 조건을 만족하면 (10분), System 클래스의 cancel(Function curFunction) 함수를 호출한다.

3. cancel(Function curFunction)에선 curFunction.changeMode() 를 실행하여 사용자가 조작중인 데이터를 저장하지 않고 defaultMode로 돌아온다.

**Comment by sys09270883** [comment]
timeout은 버튼 눌릴 때 시간을 재는 것으로 수정함
